Create CD action
Slimefun/MetricsModule pull request #2
Opened 2020-07-12 09:26 UTC by WalshyDev

You've used actions much more than me so let me know if there's anything you spot which is not correct.

2020-07-12 10:13 UTC, WalshyDev commented
Know of a good action to change the version in the pom.xml?

2020-07-12 10:18 UTC, TheBusyBiscuit requested changes

2020-07-12 10:18 UTC, TheBusyBiscuit commented on .github/workflows/maven.yml
> +    if: "! contains(toJSON(github.event.commits.*.msg), '[ci skip]')"
Iirc the exclamation mark is still broken so you may need to do == false here

2020-07-12 10:18 UTC, TheBusyBiscuit commented on .github/workflows/maven.yml
> +      run: mvn -B package --file pom.xml
Why the "--file pom.xml" here?

2020-07-12 10:18 UTC, TheBusyBiscuit commented on .github/workflows/maven.yml
> +        release_name: Build $GITHUB_RUN_NUMBER
Would add a hashtag before the number for aesthetic reasons

2020-07-12 10:20 UTC, TheBusyBiscuit commented
> Know of a good action to change the version in the pom.xml?

Well, for my builds page I use my xml-library and just change the version with that, could theoretically pack this into an action.

2020-07-12 10:21 UTC, WalshyDev commented on .github/workflows/maven.yml
> +    if: "! contains(toJSON(github.event.commits.*.msg), '[ci skip]')"
Is there an issue ticket for this somewhere?

2020-07-12 10:25 UTC, WalshyDev commented
> > Know of a good action to change the version in the pom.xml?
> 
> Well, for my builds page I use my xml-library and just change the version with that, could theoretically pack this into an action.

If you could that would be nice :heart:

2020-07-13 17:34 UTC, TheBusyBiscuit approved these changes

2020-07-13 17:34 UTC, merged